version: '2'

services:
  rpi-ffserver-armhf:
    image: rekter/ffmpeg-arm
    container_name: rpi-ffserver-armhf
    volumes:
      - ./data:/home
    read_only: false 
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      extnetwork:
        ipv4_address: 172.10.0.2
    ports:
      - "8554:8554"
    command: /home/start-ffserver.sh
  rpi-ffmpeg-armhf:
    depends_on:
       - rpi-ffserver-armhf
    image: rekter/ffmpeg-arm
    container_name: rpi-ffmpeg-rtsp
    volumes:
      - ./data:/home
    devices:
      - dev/video0:dev/video0
    read_only: false 
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      extnetwork:
        ipv4_address: 172.10.0.3
    command: 'ffmpeg -f v4l2 -i /dev/video0  -s 640x480 -r 50  -vcodec libx264 -an http://172.10.0.2:8090/feed1.ffm'

networks:
  extnetwork:
    ipam:
       config:
         - subnet: 172.10.0.0/16
           gateway: 172.10.0.1
